scan2_output: /nfs/casm/team268im/at31/bin/repos/hiscanner_demo/scan2_out/
metadata_path: /nfs/casm/team268im/at31/bin/repos/hiscanner_demo/resources/metadata.txt
outdir: /nfs/casm/team268im/at31/bin/repos/hiscanner_demo/hiscanner_out

fasta_folder: '/nfs/casm/team268im/at31/bin/repos/hiscanner_demo/fasta_split/'
mappability_folder_stem: '/nfs/casm/team268im/at31/bin/repos/hiscanner_demo/mappability/100mer.'
use_multisample_segmentation: true

rdr_only: false
binsize: 500000
chrom_list: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19"]
lambda_range: [2, 4, 8, 16, 32, 64, 128, 256, 512, 1024, 2048]
lambda_value: 1024

max_wgd: 1
batch_size: 5
depth_filter: 0
ado_threshold: 0.2
threads: 4
ado_plot_baf_distribution: true

aggregate_every_k_snp: true
k: 5

cell_groups: []
multisample_temp_dir: "temp/multisample"

keep_raw_files: false
rerun: false
keep_temp_files: false

use_cluster: false
cluster_queue: "park"
max_cluster_jobs: 100
